name: Build and Test

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        node:
          - '12'
          - '14'
          - '16'
    name: Build and Test (Node ${{ matrix.node }})
    steps:
      - name: Check out the code
        uses: actions/checkout@v2.4.0

      - name: Set up Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Update npm
        run: npm i -g npm

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run postinstall scripts
        run: npm rebuild && npm run prepare --if-present

      - name: Run tests
        run: npm test
